# Default values for padawans.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  que: 1
  http: 2

ingress:
  base_host: dev-api.igooods.ru

image:
  tag: latest
  repository: registry.gitlab.com/igooods/ruby-boilerplate
  pullPolicy: Always

app:
  envSecret: app-env

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 500Mi
